baseURL: "https://cv.aws10.asix2a25-26.cat/"
languageCode: ca
build:
  writeStats: true
title: Currículum AWS Eduardo
# Uncomment below to use aafu as hugo theme. See instructions in README.md
theme: aafu

params:
  author: Eduardo Badoyan
  description: Currículum AWS - Cloud Resume Challenge
  copyright: powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: experiences
    - item: education
    - item: projects
    - item: skills
      panel_id: skill-panel
    - item: hobbies
